config/routes.rb
Rails.application.routes.draw do
  resources :locations
  devise_for :users

  root to: "locations#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true

  geocoded_by :address
  after_validation :geocode
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  def index
    @locations = Location.all
  end

  # GET /locations/1
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  def create
    @location = Location.new(location_params)

    if @location.save
      redirect_to @location, notice: 'Location was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /locations/1
  def update
    if @location.update(location_params)
      redirect_to @location, notice: 'Location was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /locations/1
  def destroy
    @location.destroy

    redirect_to locations_url, notice: 'Location was successfully destroyed.'
  end

  private

  def set_location
    @location = Location.find(params[:id])
  end

  def location_params
    params.require(:location).permit(:title, :description, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/_header.html.erb
<style>
  .container {
      padding: 80px 0px;
      text-align: center;  
        background-color: ##8A2BE2;  
  }

.jumbotron {
    background-color: #008080;  
}

</style>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header"> 
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </div>
    <ul class='nav navbar-nav navbar-right'>
      <% if current_user %>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Register', new_user_registration_path %></li>
        <li><%= link_to 'Login', new_user_session_path %></li>
      <% end %>       
    </ul>
  </div>
</nav>

<div class="container">
  <div class="jumbotron vertical-center">
    <h1><strong>GEAR DOWN</strong></h1>      
    <p>Flight Crew Terminal Area Information </p>
  </div>
  <h2> Gear Down provides flight and ground crews with relevent information about airports and communities they are traveling to or from.</h2><br>        
  <h3>Please provide your login information below or create an account to contunue!</h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<style>
body  {
    background-image: url("photos/back.png");
    background-repeat: no-repeat;
    background-attachment: fixed;
}
</style>
  <head>


    <title>Gear Down Airport Information Serive</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <link rel='stylesheet' href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' />
    <!-- https://bootswatch.com/simplex/ -->
    <link rel='stylesheet' href='//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/yeti/bootstrap.min.css' />
    <style href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'></style>
  </head>

  <body>
   


   
    <%= render 'layouts/header' %>


    <%# <%= image_tag("photos/back.png", width: "900px") %> %>
    <div class='container'>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
        
      <%= yield %>
    </div>
  </body>
 
</html>

app/views/locations/_form.html.erb
<div class='well bs-component'>
  <%= form_for(location, html: { class: 'form-horizontal' }) do |f| %>
    <% if location.errors.any? %>
    <fieldset>
        <div id="error_explanation">
          <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

          <ul>
          <% location.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class='form-group'>
        <%= f.label :Airport_Name_or_Location, class: 'col-lg-2' %>
        <div class='col-lg-10'>
        <%= f.text_field :title, class: 'form-control', required: true %>
        </div>
      </div>

      <div class='form-group'>
        <%= f.label :"ICAO_Code", class: 'col-lg-2' %>
        <div class='col-lg-10'>
        <%= f.text_field :address, class: 'form-control', required: true %>
        </div>
      </div>

      <div class='form-group'>
        <%= f.label :description, class: 'col-lg-2' %>
        <div class='col-lg-10'>
        <%= f.text_area :description, class: 'form-control', required: false %>
        </div>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
    <fieldset>
  <% end %>
</div>

app/views/locations/_google_map.erb
<iframe
  width="600"
  height="450"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCrWc426lriWSvyKMj2WOFEbnUgOkb-DzQ
    &q=<%= @location.address %>" allowfullscreen>  
</iframe>

app/views/locations/edit.html.erb
<div class='page-header'>
  <h1>Change Airport</h1>
</div>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<div class='page-header'>
  <h1>List of Airports</h1>
</div>

<table class='table table-striped table-hover'>
  <thead>
    <tr>
      <th>Airports</th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= link_to location.title, location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %> | 
            <%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path, class: 'btn btn-primary' %>

app/views/locations/new.html.erb
<div class='page-header'>
  <h1>Enter Airport Information</h1>
  <h4>All Fields Required</h4> 
  <hr>
</div>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<div class='page-header'>
  <h1><strong><%= @location.title %><strong></h1>
</div>

<script type="text/javascript" src="https://api.checkwx.com/widgets/metartaf.js"></script>
<h3>TAF</h3>
<hr>
 <h3><div class="checkwx-container" data-type="TAF" data-station="<%= @location.address %>"></h3>
 <hr>
 <h3>METAR</h3>
 <hr>
 <h3><div class="checkwx-container" data-type="METAR" data-station="<%= @location.address %>"></h3>
<hr>
<h3>AIRPORT MAP</h3>
<hr>
<div clas='col-lg-6'>
<%= render 'google_map', location: @location %>
</div>








<div class='well'>
  <%= link_to 'Edit', edit_location_path(@location), class: 'btn btn-primary' %>|
  <%= link_to 'Back', locations_path, class: 'btn btn-primary'%>
</div>